umalista = [8.9,7,6,5,4,3,2,1]
print(umalista)
umalista.pop()
print(umalista)
umalista.pop()
print(umalista)
umalista.append(9)
umalista.append(10)
umalista.append(11)
print(umalista)
umalista.insert(6,66)
print(umalista)
umalista.pop(-3)
print(umalista)
print(len(umalista))
print(sum(umalista))

mediadalista = sum(umalista) / len(umalista)
print(mediadalista)

